<!--data와 el 속성 처리하기-->

<body>
<template id="hello">
    <h1>{{msg}} {{user}}</h1>
</template>

<div id="app">
    <hello-component v-bind:user="user"></hello-component>
</div>

<script src="/vue.js"></script>
<script>
    Vue.component('hello-component', {
        template: '#hello',
        data: function () {
            return {
                msg: 'Hello'
            }
        },

        props: ['user']
    });

    new Vue({
        el: '#app',
        data: {
            user: 'hero'
        }
    });
</script>
</body>