<html>
<head>
    <style>
        .container {
            width: 40%;
            margin: 20px auto 0px auto;
        }

        .removed label {
            text-decoration: line-through;
        }

        ul li {
            list-style-type: none;
        }

        ul li span {
            margin-left: 5px;
        }

        .footer {
            font-size: 0.7em;
            margin-top: 20vh;
        }
    </style>
</head>

<body>
<div id="app" class="container">
    <h2>{{ title }}</h2>
    <div>
        <input type="text" v-model.trim="newItem" @keyup.enter="addItem" placeholder="add shopping list item">
        <span>
            <button type="button" @click="addItem">Add!</button>
        </span>
    </div>
    <ul>
        <li v-for="item in items" :class="{ 'removed': item.checked }">
            <div>
                <label>
                    <input type="checkbox" v-model="item.checked"> {{ item.text }}
                </label>
            </div>
        </li>
    </ul>
    <div class="footer">
        <hr/>
        <em>Change the title of your shopping list here</em>
        <input v-model="title"/>
    </div>
</div>
<script src="/vue.js"></script>
<script>
    var data = {
        items: [
            {text: 'Bananas', checked: true},
            {text: 'Apples', checked: false}
        ],
        title: 'My Shopping List',
        newItem: ''
    };

    new Vue({
        el: '#app',
        data: data,
        methods: {
            addItem: function () {
                var text;

                text = this.newItem;
                if (text) {
                    this.items.push({
                        text: text,
                        checked: false
                    });
                    this.newItem = '';
                }
            }
        }
    });
</script>
</body>
</html>